# Generated by Django 6.1.1 on 2026-09-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_type', models.CharField(choices=[('weekday', 'Weekday'), ('weekend', 'Weekend'), ('holiday', 'Libur Nasional')], max_length=50)),
                ('period', models.CharField(choices=[('old_date', 'Tanggal Tua'), ('payday', 'Tanggal Gajian'), ('young_date', 'Tanggal Muda')], max_length=50)),
                ('weather', models.CharField(choices=[('clear', 'Cerah'), ('cloudy', 'Berawan'), ('rainy', 'Hujan')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_factors', to='business.business')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('business', 'date'), name='unique_external_factor_per_day')],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('recommended_qty', models.PositiveIntegerField()),
                ('confidence', models.PositiveIntegerField()),
                ('data_days_used', models.PositiveIntegerField()),
                ('factors_snapshot', models.JSONField(help_text='Snapshot dari faktor dan adjustment saat diprediksi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='business.menuitem')),
            ],
            options={
                'ordering': ['-target_date'],
                'constraints': [models.UniqueConstraint(fields=('menu_item', 'target_date'), name='unique_forecast_per_day')],
            },
        ),
    ]
