# Generated by Django 6.1.1 on 2026-09-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty_sold', models.PositiveIntegerField()),
                ('qty_produced', models.PositiveIntegerField(blank=True, null=True)),
                ('qty_leftover', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='business.menuitem')),
            ],
            options={
                'ordering': ['-date', 'menu_item__name'],
                'constraints': [models.UniqueConstraint(fields=('menu_item', 'date'), name='unique_menu_sale_per_day')],
            },
        ),
    ]
